#ifndef LIBREALSENSE2_CS_OPTIONS_DEFAULT_H
#define LIBREALSENSE2_CS_OPTIONS_DEFAULT_H

namespace librealsense
{
    const std::map<rs2_option, float> d415e_stereo_option_default = {
        {RS2_OPTION_EXPOSURE, 33000},
        {RS2_OPTION_GAIN, 16},
        {RS2_OPTION_ENABLE_AUTO_EXPOSURE, 1},
        {RS2_OPTION_VISUAL_PRESET, 0},
        {RS2_OPTION_LASER_POWER, 150},
        {RS2_OPTION_EMITTER_ENABLED, 1},
        {RS2_OPTION_FRAMES_QUEUE_SIZE, 16},
        {RS2_OPTION_OUTPUT_TRIGGER_ENABLED, 0},
        {RS2_OPTION_DEPTH_UNITS, 0.001},
        {RS2_OPTION_INTER_CAM_SYNC_MODE, 0},
        {RS2_OPTION_GLOBAL_TIME_ENABLED, 1},
        {RS2_OPTION_INTER_PACKET_DELAY, 0},
        {RS2_OPTION_PACKET_SIZE, 1500},
        {RS2_OPTION_USER_OUTPUT_LEVEL, 1},
        {RS2_OPTION_EXT_TRIGGER_SOURCE, 1},
        {RS2_OPTION_SOFTWARE_TRIGGER, 1},
        {RS2_OPTION_SOFTWARE_TRIGGER_ALL_SENSORS, 0},
        {RS2_OPTION_LINE_DEBOUNCER_TIME, 0},
        {RS2_OPTION_EXTERNAL_EVENT_BURST_COUNT, 1},
        {RS2_OPTION_METADATA_TOGGLE, 0}
    };

    const std::map<rs2_option, float> d415e_rgb_option_default = {
        {RS2_OPTION_BACKLIGHT_COMPENSATION, 0},
        {RS2_OPTION_BRIGHTNESS, 0},
        {RS2_OPTION_CONTRAST, 50},
        {RS2_OPTION_EXPOSURE, 166},
        {RS2_OPTION_GAIN, 64},
        {RS2_OPTION_GAMMA, 300},
        {RS2_OPTION_HUE, 0},
        {RS2_OPTION_SATURATION, 64},
        {RS2_OPTION_SHARPNESS, 50},
        {RS2_OPTION_WHITE_BALANCE, 4600},
        {RS2_OPTION_ENABLE_AUTO_EXPOSURE, 1},
        {RS2_OPTION_ENABLE_AUTO_WHITE_BALANCE, 1},
        {RS2_OPTION_FRAMES_QUEUE_SIZE, 16},
        {RS2_OPTION_POWER_LINE_FREQUENCY, 1},
        {RS2_OPTION_AUTO_EXPOSURE_PRIORITY, 1},
        {RS2_OPTION_INTER_CAM_SYNC_MODE, 0},
        {RS2_OPTION_GLOBAL_TIME_ENABLED, 1},
        {RS2_OPTION_INTER_PACKET_DELAY, 0},
        {RS2_OPTION_PACKET_SIZE, 1500},
        {RS2_OPTION_EXT_TRIGGER_SOURCE, 1},
        {RS2_OPTION_SOFTWARE_TRIGGER, 1},
        {RS2_OPTION_EXTERNAL_EVENT_BURST_COUNT, 1},
        {RS2_OPTION_RGB_LED_TOGGLE, 1}
    };

    const std::map<rs2_option, float> d435e_stereo_option_default = {
        {RS2_OPTION_EXPOSURE, 33000},
        {RS2_OPTION_GAIN, 16},
        {RS2_OPTION_ENABLE_AUTO_EXPOSURE, 1},
        {RS2_OPTION_VISUAL_PRESET, 0},
        {RS2_OPTION_LASER_POWER, 150},
        {RS2_OPTION_EMITTER_ENABLED, 1},
        {RS2_OPTION_FRAMES_QUEUE_SIZE, 16},
        {RS2_OPTION_OUTPUT_TRIGGER_ENABLED, 0},
        {RS2_OPTION_DEPTH_UNITS, 0.001},
        {RS2_OPTION_INTER_CAM_SYNC_MODE, 0},
        {RS2_OPTION_GLOBAL_TIME_ENABLED, 1},
        {RS2_OPTION_INTER_PACKET_DELAY, 0},
        {RS2_OPTION_PACKET_SIZE, 1500},
        {RS2_OPTION_USER_OUTPUT_LEVEL, 1},
        {RS2_OPTION_EXT_TRIGGER_SOURCE, 1},
        {RS2_OPTION_SOFTWARE_TRIGGER, 1},
        {RS2_OPTION_SOFTWARE_TRIGGER_ALL_SENSORS, 0},
        {RS2_OPTION_LINE_DEBOUNCER_TIME, 0},
        {RS2_OPTION_EXTERNAL_EVENT_BURST_COUNT, 1},
        {RS2_OPTION_METADATA_TOGGLE, 0}
    };

    const std::map<rs2_option, float> d435e_rgb_option_default = {
        {RS2_OPTION_BACKLIGHT_COMPENSATION, 0},
        {RS2_OPTION_BRIGHTNESS, 0},
        {RS2_OPTION_CONTRAST, 50},
        {RS2_OPTION_EXPOSURE, 166},
        {RS2_OPTION_GAIN, 64},
        {RS2_OPTION_GAMMA, 300},
        {RS2_OPTION_HUE, 0},
        {RS2_OPTION_SATURATION, 64},
        {RS2_OPTION_SHARPNESS, 50},
        {RS2_OPTION_WHITE_BALANCE, 4600},
        {RS2_OPTION_ENABLE_AUTO_EXPOSURE, 1},
        {RS2_OPTION_ENABLE_AUTO_WHITE_BALANCE, 1},
        {RS2_OPTION_FRAMES_QUEUE_SIZE, 16},
        {RS2_OPTION_POWER_LINE_FREQUENCY, 1},
        {RS2_OPTION_AUTO_EXPOSURE_PRIORITY, 1},
        {RS2_OPTION_INTER_CAM_SYNC_MODE, 0},
        {RS2_OPTION_GLOBAL_TIME_ENABLED, 1},
        {RS2_OPTION_INTER_PACKET_DELAY, 0},
        {RS2_OPTION_PACKET_SIZE, 1500},
        {RS2_OPTION_EXT_TRIGGER_SOURCE, 1},
        {RS2_OPTION_SOFTWARE_TRIGGER, 1},
        {RS2_OPTION_EXTERNAL_EVENT_BURST_COUNT, 1},
        {RS2_OPTION_RGB_LED_TOGGLE, 1}
    };

    const std::map<rs2_option, float> d455e_stereo_option_default = {
        {RS2_OPTION_EXPOSURE, 33000},
        {RS2_OPTION_GAIN, 16},
        {RS2_OPTION_ENABLE_AUTO_EXPOSURE, 1},
        {RS2_OPTION_VISUAL_PRESET, 0},
        {RS2_OPTION_LASER_POWER, 150},
        {RS2_OPTION_EMITTER_ENABLED, 1},
        {RS2_OPTION_FRAMES_QUEUE_SIZE, 16},
        {RS2_OPTION_OUTPUT_TRIGGER_ENABLED, 0},
        {RS2_OPTION_DEPTH_UNITS, 0.001},
        {RS2_OPTION_INTER_CAM_SYNC_MODE, 0},
        {RS2_OPTION_GLOBAL_TIME_ENABLED, 1},
        {RS2_OPTION_INTER_PACKET_DELAY, 0},
        {RS2_OPTION_PACKET_SIZE, 1500},
        {RS2_OPTION_USER_OUTPUT_LEVEL, 1},
        {RS2_OPTION_EXT_TRIGGER_SOURCE, 1},
        {RS2_OPTION_SOFTWARE_TRIGGER, 1},
        {RS2_OPTION_SOFTWARE_TRIGGER_ALL_SENSORS, 0},
        {RS2_OPTION_LINE_DEBOUNCER_TIME, 0},
        {RS2_OPTION_EXTERNAL_EVENT_BURST_COUNT, 1},
        {RS2_OPTION_METADATA_TOGGLE, 0}
    };

    const std::map<rs2_option, float> d455e_rgb_option_default = {
       {RS2_OPTION_BACKLIGHT_COMPENSATION, 0},
       {RS2_OPTION_BRIGHTNESS, 0},
       {RS2_OPTION_CONTRAST, 50},
       {RS2_OPTION_EXPOSURE, 166},
       {RS2_OPTION_GAIN, 64},
       {RS2_OPTION_GAMMA, 300},
       {RS2_OPTION_HUE, 0},
       {RS2_OPTION_SATURATION, 64},
       {RS2_OPTION_SHARPNESS, 50},
       {RS2_OPTION_WHITE_BALANCE, 4600},
       {RS2_OPTION_ENABLE_AUTO_EXPOSURE, 1},
       {RS2_OPTION_ENABLE_AUTO_WHITE_BALANCE, 1},
       {RS2_OPTION_FRAMES_QUEUE_SIZE, 16},
       {RS2_OPTION_POWER_LINE_FREQUENCY, 1},
       {RS2_OPTION_AUTO_EXPOSURE_PRIORITY, 1},
       {RS2_OPTION_INTER_CAM_SYNC_MODE, 0},
       {RS2_OPTION_GLOBAL_TIME_ENABLED, 1},
       {RS2_OPTION_INTER_PACKET_DELAY, 0},
       {RS2_OPTION_PACKET_SIZE, 1500},
       {RS2_OPTION_EXT_TRIGGER_SOURCE, 1},
       {RS2_OPTION_SOFTWARE_TRIGGER, 1},
       {RS2_OPTION_EXTERNAL_EVENT_BURST_COUNT, 1},
    };

} // ! namespace librealsense



#endif //!LIBREALSENSE2_CS_OPTIONS_DEFAULT_H
